### ISSUE TITLE
change google analytics tracking code

### ISSUE THREAD

**Issue by selvakn** [twggn/geeknight#1]
@rohitggarg / @avinash-chugh / @suchitpuri 
Can you change the google analytics tracking code, so that the stats wont interfere with Chennai's stats.

Also, it would be helpful for you guys to track.

cc: @rdsubhas

**Comment by rdsubhas** [comment]
+1 :)

**Comment by suchitpuri** [comment]
Have already done that

**Comment by jaideeprana** [comment]
@selvakn Can we close this issue, as from @suchitpuri 's comment it seems its already done.
